# Generated by Django 4.2.3 on 2023-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunler/'),
        ),
    ]
